@extends('layout.app')
@section('appContents')
<h1>Home</h1>
<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto quae modi earum laborum! Adipisci corporis, temporibus repudiandae nobis ea ratione incidunt? Rerum doloremque dignissimos modi inventore tempora, pariatur tenetur repudiandae aspernatur ad possimus maiores commodi, debitis architecto cum, quis laborum saepe facere vitae vel doloribus. Eligendi natus neque molestiae, voluptas iure non excepturi error placeat, aut distinctio tenetur sit. Inventore iusto asperiores dolore impedit nobis, ad in consectetur explicabo, tempora accusantium incidunt assumenda libero deserunt illo unde voluptatibus cupiditate? Odit quod culpa dicta aspernatur molestiae deleniti id atque libero sunt numquam accusamus a doloremque quibusdam itaque fuga, consequuntur et magni.</p>
<p>Numquam voluptatum deleniti sint minima autem totam, illum velit, distinctio voluptas in dolor tempora voluptate possimus nihil officia voluptates, cupiditate harum. Quia facilis nostrum voluptate velit ut dolorem ullam, facere earum molestias delectus quos odit rem, culpa amet vel? Corrupti, aperiam! Aut ea ut voluptates recusandae quis reprehenderit reiciendis dolores optio dicta vitae, eius officiis, illum, nemo eum iusto similique molestiae. Eius sed eligendi, recusandae illo suscipit vitae magni assumenda voluptatibus. Distinctio, illo accusantium. Hic animi accusantium doloribus alias dolore. Consectetur repellat minima et quidem doloribus vitae vel officiis dignissimos ut necessitatibus quos adipisci repudiandae excepturi, voluptas, facere odio reprehenderit!</p>
<p>Est hic corporis aliquam eius cumque dolorem? Rerum tempora consectetur dolorum atque voluptates. Eum quos nesciunt repellendus laborum! Molestiae eum veniam ullam totam beatae, mollitia ad minima provident harum sit sequi necessitatibus ipsa, error quo excepturi explicabo ex officiis voluptas consequatur! Illum, esse? Vero hic assumenda, repudiandae quisquam accusamus explicabo quis non quae veniam? Odit fuga beatae nulla perferendis ipsum quod aspernatur quibusdam iste minima dignissimos, quae odio nesciunt architecto dolorem sint reprehenderit nam provident eius consequatur ratione cumque eos hic. Optio, eveniet quae expedita consequatur sunt nulla non laborum a unde qui, assumenda numquam ipsa? At quis obcaecati repellat.</p>
<p>Iure debitis eligendi quia! Obcaecati accusantium molestiae iusto libero tempora. In sunt quis quibusdam cum eius earum perferendis! Consequuntur eligendi eos reprehenderit beatae sit ratione architecto dolores, deleniti iusto asperiores in odit corrupti optio eveniet unde veniam nemo incidunt inventore. Possimus eum cumque quos sapiente porro, quibusdam omnis autem consequatur quae quo quas tempora dolorum nulla nostrum tempore nihil? Minus eum numquam laboriosam aliquam maxime, cum quis magni? Aperiam corrupti harum inventore, amet repellendus quae suscipit aut eum voluptatibus non beatae numquam! Vitae vero, sequi, quasi illo ab assumenda libero, pariatur doloremque dignissimos laborum deleniti. Odit nisi voluptatem error quam.</p>
<p>Totam, iure reiciendis explicabo quisquam nemo, repellendus eveniet expedita tempore alias error dolorem nostrum placeat dicta numquam sapiente magnam laboriosam, consequuntur similique obcaecati accusamus neque porro autem! Consequatur, illo asperiores sed provident sapiente possimus voluptates earum laudantium, voluptas dolorem veniam? Harum magni mollitia cum atque nesciunt sit hic voluptas optio recusandae eaque, neque quibusdam est quia quidem sequi omnis sed culpa ipsa! Praesentium dolor mollitia natus aperiam voluptatibus reiciendis quo aut impedit labore nesciunt officia, eos ratione recusandae? Sunt quaerat, autem incidunt fuga expedita est, iure aliquam necessitatibus fugit corporis non natus. Quis magni incidunt tenetur ullam laboriosam corporis rem.</p>
@stop
